/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/*! @name PORTC12 (number 84), D0
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_D0_GPIO GPIOC                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_D0_GPIO_PIN_MASK (1U << 12U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_D0_PORT PORTC                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_D0_PIN 12U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_D0_PIN_MASK (1U << 12U)      /*!<@brief PORT pin mask */
                                                    /* @} */

/*! @name PORTC4 (number 76), D1
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_D1_GPIO GPIOC               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_D1_GPIO_PIN_MASK (1U << 4U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_D1_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_D1_PIN 4U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_D1_PIN_MASK (1U << 4U)      /*!<@brief PORT pin mask */
                                                   /* @} */

/*! @name PORTB9 (number 57), D2
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_D2_GPIO GPIOB               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_D2_GPIO_PIN_MASK (1U << 9U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_D2_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_D2_PIN 9U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_D2_PIN_MASK (1U << 9U)      /*!<@brief PORT pin mask */
                                                   /* @} */

/*! @name PORTB23 (number 69), D4
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_D4_GPIO GPIOB                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_D4_GPIO_PIN_MASK (1U << 23U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_D4_PORT PORTB                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_D4_PIN 23U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_D4_PIN_MASK (1U << 23U)      /*!<@brief PORT pin mask */
                                                    /* @} */

/*! @name PORTB11 (number 59), CS
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_CS_GPIO GPIOB                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_CS_GPIO_PIN_MASK (1U << 11U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_CS_PORT PORTB                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_CS_PIN 11U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_CS_PIN_MASK (1U << 11U)      /*!<@brief PORT pin mask */
                                                    /* @} */

/*! @name PORTB2 (number 55), RD
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_RD_GPIO GPIOB               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_RD_GPIO_PIN_MASK (1U << 2U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_RD_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_RD_PIN 2U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_RD_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                                   /* @} */

/*! @name PORTB3 (number 56), WR
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_WR_GPIO GPIOB               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_WR_GPIO_PIN_MASK (1U << 3U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_WR_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_WR_PIN 3U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_WR_PIN_MASK (1U << 3U)      /*!<@brief PORT pin mask */
                                                   /* @} */

/*! @name PORTA1 (number 35), D3
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_D3_GPIO GPIOA               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_D3_GPIO_PIN_MASK (1U << 1U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_D3_PORT PORTA               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_D3_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_D3_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                   /* @} */

/*! @name PORTA2 (number 36), D5
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_D5_GPIO GPIOA               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_D5_GPIO_PIN_MASK (1U << 2U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_D5_PORT PORTA               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_D5_PIN 2U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_D5_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                                   /* @} */

/*! @name PORTC2 (number 72), D6
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_D6_GPIO GPIOC               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_D6_GPIO_PIN_MASK (1U << 2U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_D6_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_D6_PIN 2U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_D6_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                                   /* @} */

/*! @name PORTC3 (number 73), D7
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_D7_GPIO GPIOC               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_D7_GPIO_PIN_MASK (1U << 3U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_D7_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_D7_PIN 3U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_D7_PIN_MASK (1U << 3U)      /*!<@brief PORT pin mask */
                                                   /* @} */

/*! @name PORTC11 (number 83), RST
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_RST_GPIO GPIOC                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_RST_GPIO_PIN_MASK (1U << 11U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_RST_PORT PORTC                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_RST_PIN 11U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_RST_PIN_MASK (1U << 11U)      /*!<@brief PORT pin mask */
                                                     /* @} */

/*! @name PORTB10 (number 58), RS
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_RS_GPIO GPIOB                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_RS_GPIO_PIN_MASK (1U << 10U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_RS_PORT PORTB                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_RS_PIN 10U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_RS_PIN_MASK (1U << 10U)      /*!<@brief PORT pin mask */
                                                    /* @} */

/*! @name PORTC16 (number 90), RX
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_RX_PORT PORTC                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_RX_PIN 16U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_RX_PIN_MASK (1U << 16U)      /*!<@brief PORT pin mask */
                                                    /* @} */

/*! @name PORTC17 (number 91), TX
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_TX_PORT PORTC                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_TX_PIN 17U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_TX_PIN_MASK (1U << 17U)      /*!<@brief PORT pin mask */
                                                    /* @} */

/*! @name PORTC1 (number 71), XP
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_XP_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_XP_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_XP_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                   /* @} */

/*! @name PORTC0 (number 70), YP
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_YP_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_YP_PIN 0U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_YP_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                                   /* @} */

/*! @name PORTE24 (number 31), YM
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_YM_PORT PORTE                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_YM_PIN 24U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_YM_PIN_MASK (1U << 24U)      /*!<@brief PORT pin mask */
                                                    /* @} */

/*! @name PORTC10 (number 82), ADC
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_ADC_PORT PORTC                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_ADC_PIN 10U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_ADC_PIN_MASK (1U << 10U)      /*!<@brief PORT pin mask */
                                                     /* @} */

/*! @name PORTD2 (number 95), ATTEN
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_ATTEN_GPIO GPIOD               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_ATTEN_GPIO_PIN_MASK (1U << 2U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_ATTEN_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_ATTEN_PIN 2U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_ATTEN_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                                      /* @} */

/*! @name PORTD3 (number 96), DIV
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_DIV_GPIO GPIOD               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_DIV_GPIO_PIN_MASK (1U << 3U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_DIV_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_DIV_PIN 3U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_DIV_PIN_MASK (1U << 3U)      /*!<@brief PORT pin mask */
                                                    /* @} */

/*! @name ADC0_DP1 (number 14), BAT
  @{ */
/* @} */

/*! @name PORTD1 (number 94), AC_DC
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_AC_DC_GPIO GPIOD               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_AC_DC_GPIO_PIN_MASK (1U << 1U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_AC_DC_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_AC_DC_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_AC_DC_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                      /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
